version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - '9000:80'
    volumes:
      - ./data/www:/var/www/html
      - ./nginx/server.conf:/etc/nginx/nginx.conf

  vue:
    build: ./vue
    volumes:
      - ./data/www:/app
    tty: true

  mysql:
    build: ./mysql/ #Dockerfileからビルドすることを示す

    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d #初期データ
    environment:
      - MYSQL_ROOT_PASSWORD=root #環境変数
